In [2]:
import numpy as np

### Basic Array Creation

In [3]:
# Numpy array is always created using a list
# A List can have multiple data types
a = [1,2,3,4.5,"Hello"]
print(a)
b = [1,2,3,4.5]
print(b)
# A Numpy array
arr = np.array([1,2,3,4])
arr

[1, 2, 3, 4.5, 'Hello']
[1, 2, 3, 4.5]


array([1, 2, 3, 4])

In [4]:
'''If we pass a List in an array that have a data type other than integer it will convert all the data in that perticular data type, if it has a
string will convert all the data in strings using unicodes and if it has a float it will convert all the data present inside the list to float'''
arr1 = np.array(a)
print(arr1)
# If it has a float it will convert all the data into float
arr2 = np.array(b)
print(arr2)

['1' '2' '3' '4.5' 'Hello']
[1.  2.  3.  4.5]


In [5]:
''' Vectors are something that is created in single one dimensional space, in simple word a list is a vector but a matrix is 2-dimensional that has 
multiple rows and colunms. we can create a matrix by creating an array inside another array '''
l = [[1,2,3],[4,5,6],[7,8,9]]
print(l)
mat = np.array(l)
print(mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array Generation Function

In [6]:
'''To generate something the first thing we can do is to use range(arange) function same as python we have to give start stop and step value'''
arr3 = np.arange(1,11)

In [7]:
'''We can generate zeros and ones for both vector and matrix using Numpy'''
# To generate zeros in vector
arr4 = np.zeros(5)
print(arr4)
# To generate ones in matrix we have to specify the number of rows and columns
arr5 = np.ones((6,8))
print(arr5)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [8]:
'''Linspace Returns evenly spaced numbers over a specified interval we have to give start,stop values and number of elements we want to have'''
arr6 = np.linspace(1,5,4) # It will give 4 elements between 1-5
arr6

array([1.        , 2.33333333, 3.66666667, 5.        ])

#### Random Generation Functions

In [9]:
'''Rnadom function will give any random numbers we just have to specify number of elements'''
# Function .rand will give number between 0 to 1 (Normalization)
np.random.rand(10)

array([0.59337965, 0.48912283, 0.61289734, 0.33550752, 0.48147969,
       0.97987907, 0.88736123, 0.64760015, 0.13528651, 0.09885997])

In [10]:
# Function .randn will give number between -3 to 3 (Standarization)
np.random.randn(10)

array([ 0.45818122,  0.30112616,  0.6398878 ,  0.51426736, -0.2647173 ,
        1.04050487,  0.87719511,  1.13753394, -0.8409195 , -0.76614659])

In [11]:
# Function.randint will give any random numbers
arr7 = np.random.randint(10) #will give only one random number from 0 to 10
print(arr7)
arr8 = np.random.randint(10,30,10) # Will give random elements between the values it can have duplicate values
print(arr8)

0
[12 22 10 27 24 15 28 29 12 21]


### Array Attributes
Attributes are kind of variables defined inside a class we dont give parenthesis() after an attribute

In [12]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
mat.shape

(3, 3)

In [14]:
mat.size

9

In [15]:
mat.dtype

dtype('int64')

### Array Methods
Methods are kind of functions defined inside a class

In [16]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# To find minimum value from the array/matrix
mat.min()

np.int64(1)

In [18]:
# To find maximum value from the array/matrix
mat.max()

np.int64(9)

In [19]:
# To find sum of all the elements of the array/matrix
mat.sum()

np.int64(45)

In [20]:
# To find sum of each rows
np.sum(mat, axis = 1)

array([ 6, 15, 24])

In [21]:
# To find sum of each coulmns
np.sum(mat,axis = 0)

array([12, 15, 18])

In [22]:
mat.std()

np.float64(2.581988897471611)

In [23]:
mat.mean()

np.float64(5.0)

In [24]:
mat.var()

np.float64(6.666666666666667)

In [25]:
'''To find the index of the minimum and the maximum value funtion like argmin and argmax are used'''
mat.argmax()

np.int64(8)

In [26]:
mat.argmin()

np.int64(0)

### Reshaping and Resizing 
As understood by name reshaping means changing the shape of an array, if we have a vector we can change the shape of it in a 2-d matrix using the reshape function we just have to make sure that the number of rows*coulmns should be equal to number of total element in the array and save it in the shape variable to resize it

In [31]:
ara = np.arange(1,31)
ara

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
ara = ara.reshape(3,10)
ara

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

### Indexing and slicing of vectors

In [35]:
ara1 = np.arange(11,21)
ara1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
#To print the number 17
ara1[6]

np.int64(17)

In [42]:
# To slice a part from the array giving the start,stop and step vlaues as python.
z= ara1[1:5]
print(z)
y= ara1[1::2]
y

[12 13 14 15]


array([12, 14, 16, 18, 20])

### Indexing and slicing of Matrix
Indexing of matrix for slicing is different from indexing of vectors we have to specify the index of both rows and columns. for example if we give ara[0] it will return all the elements from 0'th row instead of a single value(shown below) for slicing we have to specify both rows and columns value.

In [45]:
ara = ara.reshape(6,5)
ara

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [48]:
ara[0]

array([1, 2, 3, 4, 5])

In [50]:
sli = ara[2:5,1:4] #1st rows index from where we want to start:Last rows index, 1st cloumns index:last columns index
sli

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [52]:
sli1 = ara[3:,3:]
sli1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [54]:
# To select an entire column
ara[:,2]

array([ 3,  8, 13, 18, 23, 28])

### Boolean Indexing

In [71]:
arr9 = np.arange(11,21) 
arr9

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
# To take out only even numbers from the array
bool_index = arr9 % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [73]:
arr10 = arr9[bool_index]
arr10

array([12, 14, 16, 18, 20])

In [74]:
# To take out only odd numbers from the array
bool_index1 = arr9 % 2 != 0
bool_index1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [76]:
arr11 = arr9[bool_index1]
arr11

array([11, 13, 15, 17, 19])

### Array Operations

#### Arithematic Operations
Operations are performed between 2 or more objects/ arrays but there is one condition that the size of both the arrays should be equal

In [77]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [78]:
# To add both the array(same index)
a1+a2

array([ 7,  9, 11, 13, 15])

In [79]:
a1-a2

array([-5, -5, -5, -5, -5])

In [80]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [81]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [82]:
a1//a2

array([0, 0, 0, 0, 0])

In [83]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting
If we want to do some operation with the entire array and don't want to do it separately with a Loop there we can use broadcasting.

In [84]:
l = [10,20,30,40]
arr12 = np.array(l)
arr12

array([10, 20, 30, 40])

In [86]:
# We can add 10 to each element of the array arr12 at once
arr12 + 10

array([20, 30, 40, 50])

In [88]:
arr13 = np.arange(1,26).reshape(5,5)
arr13

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [89]:
arr13 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

### Matrix Operations

In [91]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
mat1

array([[1, 2],
       [3, 4]])

In [92]:
mat2

array([[5, 6],
       [7, 8]])

In [95]:
''' Multiplication in matrix uses @ symbol (1*5+2*7, 1*6+2*8)
                             (3*5+4*7, 3*6+2*8) '''
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [96]:
# Another method to do the same is
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [103]:
# To change a row into a column transpose function is used
w = ara.reshape(3,10)
w

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [102]:
w.T

array([[ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29],
       [10, 20, 30]])

### Advance Array Manipulation
#### Stacking Array
we can not stack matrix we can only stack vectors, stacking simply means joining the 2 vectors using different methods

In [110]:
a1

array([1, 2, 3, 4, 5])

In [111]:
a2

array([ 6,  7,  8,  9, 10])

In [112]:
# Joins the arrays vertically
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [113]:
# Jions the arrays horizontally
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
# Joins the arrays by coulmn 
np.column_stack((a1,a2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### Splitting Array
As clear by its name splitting means dividing the array 

In [116]:
np.hsplit(arr12,2)

[array([10, 20]), array([30, 40])]

In [118]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [121]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]