In [1]:
import numpy as np

#### Valid Sudoku

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])            

In [5]:
s.sum()

np.int64(405)

In [10]:
t = np.sum(s,axis = 1)
t == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [11]:
t = np.sum(s, axis = 1)
for i in t:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for rows")

Sudoku is valid for rows


In [13]:
u = np.sum(s, axis = 0)
for i in u:
    if i == 45:
        print("Sudoku is valid for columns")
        break
else:
    print("Sudoku is not valid")

Sudoku is valid for columns


In [15]:
slice1 = s[0:3,:3]
slice1

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [18]:
for i in range(0,9,3):
    for j in range(0,9,3):
        x = s[i:i+3,j:j+3]
        print(x.sum())

45
45
45
45
45
45
45
45
45


#### General Question

In [43]:
# COlumns: [Age, Maths marks, Science marks]
data = np.array([
    [18,85,79],  #Student1
    [19,92,88],  #Student2
    [17,76,95],  #Student3
    [18,65,70],  #Student4
    [20,90,85]   #Student5
])

In [21]:
# Get the shape of the matirx
np.shape(data)

(5, 3)

In [23]:
# Find the average age of the students
np.mean(data[:,0])

np.float64(18.4)

In [24]:
# Extract Maths marks of all the students
d1 = data[:,1]
d1

array([85, 92, 76, 65, 90])

In [25]:
# Find the highest Science marks
np.max(data[:,2])

np.int64(95)

In [26]:
# Get details of students who got more than 90 marks in Maths
data[d1>90]

array([[19, 92, 88]])

In [29]:
# Increase maths marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 79],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [33]:
# Find how many students are younger than 19
len(data[data[:,0] < 19])

3

In [35]:
# Calculate the average marks in each subject(column-wise).( for column axis is 0, for rows axis is 1)
np.mean(data[:,1:], axis=0)

array([86.6, 83.4])

In [36]:
# Get data of students who got atleast 80 in both subjects
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [45]:
# Replace all Science marks less than 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 79],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])